"""initial_migration

Revises:
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Уникальный идентификатор задачи"
        ),
        sa.Column(
            "title", sa.String(length=255), nullable=False, comment="Название задачи"
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="Описание задачи"),
        sa.Column(
            "priority",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="task_priority"),
            nullable=False,
            comment="Приоритет задачи",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "PENDING",
                "IN_PROGRESS",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="task_status",
            ),
            nullable=False,
            comment="Текущий статус задачи",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время создания задачи",
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Время начала выполнения задачи",
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Время завершения задачи",
        ),
        sa.Column(
            "result",
            sa.Text(),
            nullable=True,
            comment="Результат выполнения задачи (JSON или текст)",
        ),
        sa.Column(
            "error_message",
            sa.Text(),
            nullable=True,
            comment="Сообщение об ошибке (если статус FAILED)",
        ),
        sa.Column(
            "error_details",
            sa.Text(),
            nullable=True,
            comment="Подробная информация об ошибке (стек трейс, и т.д.)",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    # ### end Alembic commands ###
